### ISSUE TITLE
Extension crashes on GNOME 40

### ISSUE THREAD

**Issue by alizehctl** [tarelda/todoist-indicator#3]
The extension is unable to run on GNOME 40, even after manually changing the shell version in `metadata.json`

```json
{
  "name": "Todoist",
  "description": "Lists tasks from Todoist task manager",
  "shell-version": ["40.4"],
  "uuid": "todoist@tarelda.github.com",
  "settings-schema": "org.gnome.shell.extensions.todoist"
}
```

![image](https://user-images.githubusercontent.com/31581044/137463493-4b471fae-3e27-4aec-8de2-e5d67e564972.png)

**Comment by tarelda** [comment]
@aadilayub I don't use GNOME 40 yet and this extension is not yet compatible with it. I can't give ETA when I will get around to port it.

**Comment by tarelda** [comment]
I updated to 3.36 and had exact same error. Fixed it and pushed into the main repository. Can you check @aadilayub if it works on 40 after patching the metadata?

**Comment by tarelda** [comment]
@aadilayub,  37540843c05d227c7e2bf02105f8ea48c240db50 should also fix #2 .

**Comment by alizehctl** [comment]
I don't get this error anymore! However, I get this error when I try to open the preferences:

The settings of extension todoist@tarelda.github.com had an error:
```
TypeError: widget.show_all is not a function
```

Stack trace:
```
buildPrefsWidget@/home/aadil/.local/share/gnome-shell/extensions/todoist@tarelda.github.com/prefs.js:85:12
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I'm currently using GNOME 41.2

**Comment by tarelda** [comment]
@aadilayub  [well porting guide didn't mention that function was removed](https://gjs.guide/extensions/upgrading/gnome-shell-40.html#show-all-and-destroy) ...

Can you try to modify function buildPrefsWidget in prefs.js as follows:


```
function buildPrefsWidget() {
    let widget = new TodoistPrefsWidget();
    if(typeof widget.show_all != "undefined") widget.show_all();
    return widget;
}
```

?

**Comment by alizehctl** [comment]
Yes that worked!
