### ISSUE TITLE
Incorrect task count

### ISSUE THREAD

**Issue by alizehctl** [tarelda/todoist-indicator#4]
This may be related to the change to the `buildPrefs` function I made in #3, but now after I refreshed the extension, it shows 'no due tasks'. Logging in and out of GNOME shell did not make a difference.

![Screenshot from 2021-12-30 15-23-20](https://user-images.githubusercontent.com/31581044/147743230-fa5148be-045a-414e-867f-28291d7b807f.png)

**Comment by tarelda** [comment]
@aadilayub Counter shows only count of the tasks that are past their due time.

**Comment by alizehctl** [comment]
Ah of course. Silly me.

Thanks for all the help! I guess I should fork and make some changes.
